### PR TITLE
zcash_protocol: Set the public mainnet activation height for NU6

### LINKED ISSUE #1356: librustzcash consensus support for NU6

### PR DESCRIPTION
**Pull request by str4d**
Closes #1356.

### CODE REVIEW

**Review by daira — CHANGES_REQUESTED** [review]
This is blocked on getting the mainnet FPF funding address. I know that this crate doesn't need that address (nor does anything else in librustzcash), but without it the NU6 consensus changes are not well-defined on mainnet.

**Comment by str4d** [comment]
> This is blocked on getting the mainnet FPF funding address

We have that address now: https://github.com/zcash/zcash/pull/6951/files#diff-ff53e63501a5e89fd650b378c9708274df8ad5d38fcffa6c64be417c4d438b6dR253-R255

**Review by nuttycom — APPROVED** [review]
utACK

**Review by daira — APPROVED** [review]
utACK

**Pull request merged**
