### PR TITLE
Migrate to blake2b_simd and blake2s_simd crates

### LINKED ISSUE #67: Bring fork of blake2_rfc in as a git subtree
We do this for other stuff, and I think this should be no exception. It avoids me having to check hashes in [PRs like this](https://github.com/zcash/librustzcash/blob/3d39706aeeb8a1e56b65192b02c1a437796191d9/zcash_proofs/Cargo.toml#L16).

### PR DESCRIPTION
**Pull request by str4d**
The primary reason for migrating is that these crates provide APIs for
setting the personalisation string. This enables us to depend solely on
published crates, and thus publish our own crates. (In order for a crate
to be published, it can't depend on unpublished ones.)

The SIMD implementations are ported from libsodium.

Closes #67.

### CODE REVIEW

**Comment by daira** [comment]
> This enables us to depend solely on published crates, and thus publish our own crates.

Do you mean "and thus avoid the need to publish"?

**Comment by daira** [comment]
There's a mixture of "chained" and "imperative" styles in how the hash object is used. The chained style looks much nicer; do we want to switch to that consistently? Does not block.

**Comment by str4d** [comment]
Rebased on master to fix merge conflict, which required applying the changes in this PR to the changes made in #69.

**Comment by str4d** [comment]
cc @gtank

**Comment by str4d** [comment]
Rebased on master to fix merge conflicts, and also bumped the minimum Rust version to 1.36 (as we will be using it for the now-stable `alloc` crate).

**Pull request merged**
