### PR TITLE
Update DEFAULT_FEE to 10_000 from 1000

### PR DESCRIPTION
**Pull request by AloeareV**
This makes the default fee equal to the minimum possible zip317 fee.

### CODE REVIEW

**Comment by nuttycom** [comment]
Tests are failing

**Comment by nuttycom** [comment]
This can be rebased now.

**Comment by AloeareV** [comment]
> This can be rebased now.

Great, rebased!

**Comment by AloeareV** [comment]
D'oh! Local test run was non-comprehensive. Fixed!

**Review by nuttycom — APPROVED** [review]
utACK

I think that this is an acceptable change. Overall what we really need to do is get rid of `DEFAULT_FEE` entirely, but for the moment this change puts us in a state that's arguably better than the existing `DEFAULT_FEE` value.

**Comment by AloeareV** [comment]
> utACK
> 
> I think that this is an acceptable change. Overall what we really need to do is get rid of `DEFAULT_FEE` entirely, but for the moment this change puts us in a state that's arguably better than the existing `DEFAULT_FEE` value.

Yeah, this is intended as a bandaid. We're in a similar situation in zingo where the next release will just hardcode a fee of 10_000 instead of 1_000, and that'll be functional enough that full support for zip317 fees can wait for us to be careful about implementing it right

**Comment by AloeareV** [comment]
@nuttycom Is this ready to merge, or is it awaiting another reviewer?

**Comment by daira** [comment]
I will file a PR to revert this and then do the rename.

**Pull request merged**
