### PR TITLE
Convert the repo into a Cargo workspace

### PR DESCRIPTION
**Pull request by str4d**
The `librustzcash` crate is now a library inside the workspace.

Several new libraries have been created, which we can refactor existing code into. We can also reorganise code between them more seamlessly than if they were split across several repositories.

If we later want to extract a library into a separate repository, we can use `git subtree split`.

### CODE REVIEW

**Comment by ebfull** [comment]
ACK

**Comment by str4d** [comment]
I added the `pairing`, `bellman` and `sapling-crypto` crates to the workspace as git subtrees using the following commands:

```
$ git subtree add -P pairing https://github.com/zkcrypto/pairing.git 09b6e6f9212020f385218e5cf5287e381ccd312b
$ git subtree add -P bellman https://github.com/zkcrypto/bellman.git master
$ git subtree add -P sapling-crypto https://github.com/zcash-hackworks/sapling-crypto.git master
```

and then modified all the crates in the workspace to correctly depend on each other.

**Comment by ebfull** [comment]
Why did we suddenly inherit all these new packages in `Cargo.lock`? Is there any way to avoid that so that this PR is a no-op in terms of behavior and dependencies?

**Comment by ebfull** [comment]
Nevermind, I guess we can't avoid it. Cargo will want all the `dev-dependencies` in `Cargo.lock` for the packages we brought in, and we want that anyway for CI to work predictably.

There are some packages that could be updated, but we shouldn't do that in this PR.

Side note, here is what gets compiled now:

```
   Compiling typenum v1.10.0
   Compiling num-traits v0.2.5
   Compiling libc v0.2.40
   Compiling num-integer v0.1.39
   Compiling nodrop v0.1.12
   Compiling byte-tools v0.2.0
   Compiling num-bigint v0.2.0
   Compiling byteorder v1.2.2
   Compiling futures v0.1.21
   Compiling opaque-debug v0.1.1
   Compiling crossbeam v0.3.2
   Compiling bit-vec v0.4.4
   Compiling constant_time_eq v0.1.3
   Compiling lazy_static v1.0.0
   Compiling zcash_proofs v0.0.0 (file:///home/sean/Shared/librustzcash/zcash_proofs)
   Compiling zcash_primitives v0.0.0 (file:///home/sean/Shared/librustzcash/zcash_primitives)
   Compiling zcash_wallet v0.0.0 (file:///home/sean/Shared/librustzcash/zcash_wallet)
   Compiling arrayvec v0.4.7
   Compiling rand v0.4.2
   Compiling num_cpus v1.8.0
   Compiling blake2-rfc v0.2.18 (https://github.com/gtank/blake2-rfc?rev=7a5b5fc99ae483a0043db7547fb79a6fa44b88a9#7a5b5fc9)
   Compiling generic-array v0.9.0
   Compiling block-cipher-trait v0.5.3
   Compiling digest v0.7.2
   Compiling aes-soft v0.2.0
   Compiling pairing v0.14.2 (file:///home/sean/Shared/librustzcash/pairing)
   Compiling aes v0.2.0
   Compiling futures-cpupool v0.1.8
   Compiling fpe v0.1.0
   Compiling bellman v0.1.0 (file:///home/sean/Shared/librustzcash/bellman)
   Compiling sapling-crypto v0.0.1 (file:///home/sean/Shared/librustzcash/sapling-crypto)
   Compiling zip32 v0.0.0 (file:///home/sean/Shared/librustzcash/zip32)
   Compiling librustzcash v0.1.0 (file:///home/sean/Shared/librustzcash/librustzcash)
```

I'd love for us to eventually do the following:

1. Figure out our `blake2-rfc` dependency which is currently pointing to a revision on gtank's github.
2. Remove `futures*` and `crossbeam`
3. Remove `libc` (we actually don't need it for anything, afaik)
4. Remove `generic-array` and `typenum` unless we actually need it for something.
5. Upgrade to rand 0.5
6. Remove `bit-vec` or implement it ourselves
7. Perhaps other internalizations of external crates that I don't want to depend on, like isolated implementations of hash functions etc. that have wonky APIs and bring in dependencies that we don't really need.
8. Remove any `num-*` crates, these are huge and we shouldn't need them for anything during runtime.

**Pull request merged**
