### PR TITLE
Only require `alloc` instead of `std` where useful

### PR DESCRIPTION
**Pull request by str4d**
This enables these crates to be used in environments like hardware wallets.

### CODE REVIEW

**Review by nuttycom — APPROVED** [review]
utACK 97aab07cc7dada5824d4bb23394d35cb731dcc46

**Review by nuttycom — DISMISSED** [review]
re-utACK b04cf09fcbae6036a3711c04d0a47def629f77b8

**Review by nuttycom — APPROVED** [review]
re-utACK 51b57a98b1f16caeb5fce6debc73fdd82c3c0e45

**Review by daira — COMMENTED** [review]
Post-hoc ACK. Please document this in the changelog.

**Pull request merged**
