### PR TITLE
zcash_primitives: Use sapling::NoteValue instead of bare u64

### PR DESCRIPTION
**Pull request by nuttycom**
Builds upon #1014

### CODE REVIEW

**Comment by zancas** [comment]
Hi @nuttycom we're having [under/over]-flow panics in `zingolib` so we're quite interested in this upgrade!  Can @AloeareV or I help move it along?

**Comment by AloeareV** [comment]
Does `sapling::NoteValue` need to be a distinct type from `NonNegativeAmount`?

**Comment by nuttycom** [comment]
> Does `sapling::NoteValue` need to be a distinct type from `NonNegativeAmount`?

The intent is that the `sapling` module is soon going to be factored out into a separate `sapling-crypto` crate, following much the same design as `orchard`. Sapling note values are not internally (within the ZK circuit) bounded above by `MAX_MONEY`; the value balance rules are enforced at the consensus level, so semantically these _are_ different types (and the dependency graph will reflect that better once `sapling-crypto` is factored out.)

**Review by str4d — APPROVED** [review]
utACK caee90dce9b33f81d99369c5410d3aa9cb8d0215

**Pull request merged**
