### PR TITLE
Sapling prover cleanups

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Comment by str4d** [comment]
[Force-pushed](https://github.com/zcash/librustzcash/compare/a610891350e29320ad35d41677660648598f6abd..fff3ed742f212e56dd2c4c4cafb7828fd508beec) to fix intra-doc links.

**Comment by str4d** [comment]
[Rebased](https://github.com/zcash/librustzcash/compare/fff3ed742f212e56dd2c4c4cafb7828fd508beec..6e42d839cd054c5202e6a9c4574c568a476e2487) to fix changelog merge conflicts.

The first commit now stores its changelog update in its commit message, testing the suggestion in https://github.com/zcash/librustzcash/issues/1032#issuecomment-1793100445. The second commit is a "replace changes with removal" commit, so I'm not currently sure how best to reflect that in a commit message.

**Review by nuttycom — APPROVED** [review]
utACK 6e42d839cd054c5202e6a9c4574c568a476e2487

**Comment by str4d** [comment]
There's one small broken intra-doc link; I'll fix it in the next PR.

**Pull request merged**
