### PR TITLE
Bump Rust to 1.37 on CI

### PR DESCRIPTION
**Pull request by NikVolf**

### CODE REVIEW

**Comment by str4d** [comment]
What functionality from 1.37 are you proposing that we depend on, such that it requires raising our minimum supported Rust version?

**Comment by NikVolf** [comment]
See building error in #118

**Comment by str4d** [comment]
To answer my own question, the feature @NikVolf wants is [referring to `enum` variants through `type` aliases](https://blog.rust-lang.org/2019/08/15/Rust-1.37.0.html#referring-to-enum-variants-through-type-aliases).

cc @ebfull on whether this is sufficient reason for bumping the MSRV.

**Comment by ebfull** [comment]
This is fine... we'll probably keep bumping the minimum required Rust version at least for the near future.

**Pull request merged**
