### PR TITLE
zcash_client_backend: Migrate to `tonic 0.12` with `http 1`

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Comment by str4d** [comment]
This conflicts with #1422 (in dependency updates), and it would be better to merge this PR before #1422.

**Comment by str4d** [comment]
Build is failing on WASM because somewhere in the dependency changes, `tokio` is getting more feature flags enabled (possibly the default features). I'm trying to figure out what is causing this.

**Comment by str4d** [comment]
The WASM build failure is due to https://github.com/hyperium/tonic/issues/1783. In the interim, I've disabled the feature flag in CI.

**Review by nuttycom — APPROVED** [review]
utACK 270eec25748d38f5d31ec3d71bc90e631f7fe3f1

**Pull request merged**
