### PR TITLE
Disable `sapling-crypto` default features by default

### PR DESCRIPTION
**Pull request by str4d**
The only default-enabled feature flag in `sapling-crypto` is the `multicore` feature flag, which we re-export in each crate that includes proof creation. We need to disable it as a default feature of our dependency in order to enable it to be correctly disabled when a user of e.g. `zcash_primitives` disables its default features.

### CODE REVIEW

**Review by nuttycom — APPROVED** [review]
utACK

**Comment by str4d** [comment]
The `cargo vet` issue I'm not going to resolve in this PR, as I expect it would cause conflicts with #1392.

**Review by nuttycom — APPROVED** [review]
utACK

**Comment by str4d** [comment]
`8b2188a0f34fea2cebbf48a9945c75715f92992e` published as `zcash_primitives-0.15.1`.

**Pull request merged**
