### PR TITLE
zcash_proofs: Temporarily fix params download

### PR DESCRIPTION
**Pull request by upbqdn**
The implementation of `io:Read` for `ResponseLazyReader` used to return
only one byte regardless of the size of the provided `buf`, which
degraded the performance of loading the response.

This change makes use of the provided `buf`. On my machine with Rust
1.64, the downloading speed went up from ~100 KiB/s to ~2 MiB/s.
However, as before this change, the process still uses 100% of a single
CPU thread when downloading the response. The most likely reason is that
we still manually read each byte of the response. I can download the
same data with ~ 50 MiB/s on my machine using a different HTTP client.

This fix seems to be sufficient for now.

### CODE REVIEW

**Review by nuttycom — APPROVED** [review]
utACK

**Comment by nuttycom** [comment]
Clippy lints need fixing.

**Comment by upbqdn** [comment]
> Clippy lints need fixing.

It looks like `codecov` is reporting untested changes. I didn't figure out how I could fix those, unfortunately.

**Comment by str4d** [comment]
@upbqdn The clippy lint CI check is also failing:

image

**Comment by upbqdn** [comment]
Thanks, I overlooked that check.

**Review by daira — APPROVED** [review]
utACK

**Pull request merged**
