### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Comment by str4d** [comment]
I removed the commit that updated to `quickcheck 1.0` because it is causing some quickcheck tests in `zcash_history` to lock up CPU and slowly eat all memory. We should migrate those tests to `proptest` instead.

**Comment by str4d** [comment]
The `ff` dependency tree update (the first commit in this PR) appears to cause a noticeable regression in the `sapling` proving benchmark (almost 50% slower in single-threaded mode on my desktop, 20% slower with my 12 threads, 10% slower for @ebfull's 32 threads). It does not appear to be related to the now-default-on `endo` flag in `bls12_381`, and it doesn't go away when benchmarking `create_proof` instead of `create_random_proof` (so it isn't related to the `getrandom` version bump).

**Comment by str4d** [comment]
@daira and I did some testing, and it now appears that the cause of the slowdown is `bitvec 0.20`. I see the same 20%-ish slowdown on my machine when specifically benchmarking `bellman::multiexp` with 2^16 scalar/base pairs, and it goes away if I switch `ff` and `bellman` to `bitvec 0.19`.

**Comment by str4d** [comment]
We have a few options:
- Merge this as-is, and accept the regression for now. All users of these crates have the regression.
- Merge this and then make a branch that rolls us back to 0.19, and use that branch in `zcashd`. Anyone relying on the published crates would see a regression, but binary users (like `zcashd` or the mobile SDKs) could patch it out.
- Don't merge this until the regression is fixed upstream.

I'm personally inclined to go with option 2, since we can't currently address this in the published crates without a breaking change to `ff`, and it may be that `bitvec` can fix this in a non-breaking way with a point release.

**Comment by str4d** [comment]
I now believe it's unlikely that `bitvec` would fix this in a point release, given that they have released `0.21`. We haven't had time to look into this performance issue ourselves, but I'm currently of the opinion that we should just get this merged and out (so that downstream users can use the updated crates, for example to enable [building on `armv8m`](https://github.com/zkcrypto/ff/pull/50)).

**Comment by daira** [comment]
In my experience, lost performance from regressions is very hard to get back, and this one is quite significant.

To what extent are we actually depending on `bitvec`? When I looked at it it seemed incredibly complicated for what it does.

**Comment by nuttycom** [comment]
Is there a concrete problem with our continuing to use the old dependency version? Is it not possible to update other dependencies, or do third-party dependencies that are out of our control depend on a newer bitvec? Also, I thought that even if that were the case that Cargo was able to solve this kind of problem?

**Comment by daira** [comment]
`bitvec` 0.20.0 was [almost a complete rewrite](https://github.com/bitvecto-rs/bitvec/blob/develop/CHANGELOG.md#020). I don't know whether it's possible to support `armv8m` with 0.19.4. That's partly why I asked how much we depend on it; it's possible that we could strip out the dependency and write much simpler helpers to iterate over bit/word arrays in completely portable Rust. (As one possible strategy, we could look at what code `bitvec` 0.19.4 generated for our specific word sizes, and copy that.)

**Comment by str4d** [comment]
@nuttycom and I looked at this again in our pairing, and it appears that `bitvec 0.22` solves the performance problem; in fact it appears to be slightly _faster_ than `bitvec 0.19` which we currently depend on!

So the resolution of the performance problem will be to upgrade to `bitvec 0.22`, which requires concrete changes to the following crates:
- `ff 0.10` minor release (since this is a breaking change as `bitvec` is in the public API)
  - This will require breaking bumps to `group`, `pairing`, `bls12_381`, `jubjub`, `bellman`
- `bellman 0.10` minor release (it uses `bitvec 0.20` internally, and also suffers from the performance issue)
- `jubjub 0.7` minor release (`bitvec` is used internally, and due to the `funty` issue we need all our in-tree `bitvec` dependencies to move at the same time)
  - We need to make a breaking release to `jubjub` anyway as we need to make the ZIP 216 change.

We will also need to temporarily remove support for parsing ZIP 321 URLs from `zcash_client_backend` in order to publish that crate, as `nom` has not yet upgraded its `bitvec` dependency (due to MSRV conflicts), and thus would cause a `funty` conflict (@nuttycom and I spent quite some time trying to avoid this). Alternatively we can just not publish `zcash_client_backend` and `zcash_client_sqlite` and have them depend on a fork of `nom` with upgraded `bitvec` (which would be fine for the mobile SDKs, which have depended on forks in the past).

In any case, I propose that we merge this PR as-is (perf regression and all), so that we unblock merging in `orchard` crate work (which currently depends on `ff 0.9` et al), and then we can update the full stack once we are ready to do so.

**Review by nuttycom — APPROVED** [review]

**Review by daira — APPROVED** [review]
utACK. I approve the plan in https://github.com/zcash/librustzcash/pull/334#issuecomment-844377077 (preferably with the "depend on a fork of `nom`" alternative, but we can decide that separately).

**Review by ebfull — APPROVED** [review]

**Pull request merged**
