### PR TITLE
Migrate to ff and group crates

### PR DESCRIPTION
**Pull request by str4d**
- Updates `pairing` to match its current master
- Pulls in the following PRs:
  - https://github.com/zkcrypto/pairing/pull/91
  - https://github.com/zkcrypto/bellman/pull/25
- Migrates remaining crates to use `ff` crate
- Pulls in the `ff` and `group` crates into the workspace.

### CODE REVIEW

**Comment by str4d** [comment]
Force-pushed to update the commit date of the last commit, in order to trigger a Travis CI build.

**Comment by str4d** [comment]
The build failed because while this branch works as-is, #39 (which was merged into master after this PR was created) added additional imports that need changing. #30 will have a similar effect, so I will rebuild this PR once #30 is merged, before creating any subsequent PRs.

**Comment by str4d** [comment]
Force-pushed to rebuild this PR on top of current master (taking into account #39 and #30). I also pulled the `ff` and `group` crates into the workspace at @ebfull's request.

**Comment by ebfull** [comment]
ACK!

**Comment by str4d** [comment]
Note to reviewers: most of the commits in this PR are only here because we pulled in the history of `ff` and `group`. Suggested review strategy:

- Review https://github.com/zkcrypto/pairing/pull/91
- Review https://github.com/zkcrypto/bellman/pull/25
- Verify that these `git subtree` commits correctly correspond to their upstream sources:
  - fe16e4a412c91dc4d5e441cadc575fc8b87cccd5 (pulls in current pairing master)
  - 794cf79db2295642874e590275e41c266898d254 (pulls in https://github.com/zkcrypto/pairing/pull/91)
  - 76cd0d92bb1d242b43686efd327bae4a9c1af330 (pulls in https://github.com/zkcrypto/bellman/pull/25)
- Review other commits after fe16e4a412c91dc4d5e441cadc575fc8b87cccd5 that modify the files once inside the cargo workspace.

**Comment by bitcartel** [comment]
cargo test reports:
``
test circuit::sprout::test_sprout_constraints ... ok

failures:

---- circuit::uint32::test::test_uint32_shr stdout ----
thread 'circuit::uint32::test::test_uint32_shr' panicked at 'attempt to shift right with overflow', sapling-crypto/src/circuit/uint32.rs:659:42
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    circuit::uint32::test::test_uint32_shr

test result: FAILED. 86 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by str4d** [comment]
@bitcartel that is #52, not caused by this PR. `cargo test --release` should pass.

**Comment by Eirik0** [comment]
Not sure if it's just me but I am getting the error: `Commits that don’t share a common merge base with the base branch are not supported.` When I try to look commit by commit.

**Comment by str4d** [comment]
@Eirik0 That's because this PR uses `git subtree` to import the history of the `ff` and `group` crates (per @ebfull's request), meaning that almost all of the commits in the PR are from a different history, and thus `don't share a common merge base with the base branch`.

**Comment by Eirik0** [comment]
Got it. Thank you!

**Pull request merged**
