### PR TITLE
Retrieve nullifiers for all unconfirmed notes.

### PR DESCRIPTION
**Pull request by nuttycom**
Previously we were retrieving nullifiers for notes that were not
marked spent, but not checking against whether the spending
transaction had been included in a block.

### CODE REVIEW

**Comment by pacu** [comment]
image
Reporting successful fix on bug https://github.com/zcash/ZcashLightClientKit/issues/255

**Review by str4d — APPROVED** [review]
utACK

**Comment by gmale** [comment]
@nuttycom @str4d How as this not always a problem? Were we previously inserting nullifiers when we created a spend?

**Comment by str4d** [comment]
We've always inserted nullifiers for notes as we receive them. This bug was specifically that we were only checking for spent nullifiers that we didn't spend ourselves! E.g. they were spent by another wallet with the same seed phrase, and we saw the nullifier in the chain. It didn't matter for spends with change because we'd detect those transactions due to trial decryption and mark them as mined.

**Comment by gmale** [comment]
That would suggest that this was always a problem though, right?

Yet it hasn't. And isn't reproducing in Android builds from a few months ago (I can double-check this but I'm fairly sure that's the case). 

The fix makes sense. The description makes sense.

What doesn't make sense is why we wouldn't have seen this fairly obvious bad behavior (a max transaction remaining pending) in the last 15+ months.

**Comment by str4d** [comment]
Is the Data Access API integration a boundary for this problem? That would be the most obvious place I would think could be hiding some other problem they was introduced, or perhaps removed some unspecified behaviour that happened to be masking or bypassing the bug in the old code.

**Comment by gmale** [comment]
Possibly. I'll make a note to check. Seems worth investigating.

**Pull request merged**
